[project]
name = "python-lab-2"
version = "1.1.0"
description = "Terminal 3000"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.2",
    "pytest-mock>=3.15.1",
    "argparse>=1.4.0"
]

[tool.coverage.report]
fail_under = 80.0
precision = 2
